version: "3.9"

services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app

  db:
    image: "postgres:11"
    restart: always
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
